config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users do 
    resources :profile 
  end 
  

  root 'pages#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user

		BUISNESS_TYPES = [['Orkuiðnaður'], ['Framleiðsla og vinnsla málma'], ['Jarðefnaiðnaður'], ['Efnaiðnaður'], ['Úrgangsstarfsemi'], ['Verslun/þjónusta'], ['Önnur starfsemi'], ['Annað']]

	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

        
  			has_one :profile
  			accepts_nested_attributes_for :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
	before_action :authenticate_user!

	#before_action :only_current_user

	def new
		#form where a user can fill put their pwn profile.

		@user = User.find(params[:user_id]) # Finnur hver er userinn sem er loggaður inn, reaching in to the url and grabbs user.
		@profile = Profile.new
	
	end

	def show
		@user = User.find(params[:id])
		@profile = @user.profile
		user_profile_path(current_user.id,current_user.profile.id)
	end

	def create
		@user = User.find(params[:user_id])
		@profile = @user.build_profile(profile_params)

		#Lecture 159 User show action next :))))
		if @profile.save
			flash[:success] = "Profile updated"
			redirect_to user_path(params[:user_id]) #fer á user/show.html.erb
		else
			render action: :new

		end

	end

	def edit
		@user = User.find(params[:user_id])
		@profile = @user.profile

	end

	def update
		@user = User.find(params[:user_id])
		@profile = @user.profile


		if @profile.update_attributes(profile_params)
			flash[:success] = "Profile Updated!"
			redirect_to user_path(params[:user_id])
		else
			render action :edit
		end		
	end


	private

		def profile_params
			params.require(:profile).permit(:company_name, :address, :city, :postalcode, :permit_publisher, :permit_monitor, :contact_person, :contact_email, :phone_number, :buisness_type, :board_member, :description, :permit_duration)
		end

		def only_current_user

			@user = User.find(params[:user_id])
			redirect_to(root_url) unless @user == current_user
		end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!

	#before_action :only_current_user

	def new
		#form where a user can fill put their pwn profile.

		@user = User.find(params[:user_id]) # Finnur hver er userinn sem er loggaður inn, reaching in to the url and grabbs user.
		@profile = Profile.new
	
	end

	def show
		@user = User.find(params[:id])
		@profile = @user.profile
		profile_path(current_user) 
	end

	def create
		@user = User.find(params[:user_id])
		@profile = @user.build_profile(profile_params)

		#Lecture 159 User show action next :))))
		if @profile.save
			flash[:success] = "Profile updated"
			redirect_to user_path(params[:user_id]) #fer á user/show.html.erb
		else
			render action: :new

		end

	end

	def edit
		@user = User.find(params[:user_id])
		@profile = @user.profile

	end

	def update
		@user = User.find(params[:user_id])
		@profile = @user.profile


		if @profile.update_attributes(profile_params)
			flash[:success] = "Profile Updated!"
			redirect_to user_path(params[:user_id])
		else
			render action :edit
		end		
	end


	private

		def profile_params
			params.require(:profile).permit(:company_name, :address, :city, :postalcode, :permit_publisher, :permit_monitor, :contact_person, :contact_email, :phone_number, :buisness_type, :board_member, :description, :permit_duration)
		end

		def only_current_user

			@user = User.find(params[:user_id])
			redirect_to(root_url) unless @user == current_user
		end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password)
  end

  def show
    
  end

   protected

  

  def after_sign_up_path_for(resource)
    redirect_to user_profile_path(current_user.id,current_user.profile.id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  
  

	def index
		@users = User.all
    @users = User.order('created_at DESC').paginate(page: params[:page], per_page: 30)

    
	end

    def create
   
    end


	def show
   # @user = current_user
		@user = User.find(params[:id])
	  @users = User.order('created_at DESC').paginate(page: params[:page], per_page: 30)
    #@electro_total = current_user.electros.sum(:electricity_kwst) 
    #@paper = current_user.papers.build
    #@electro = current_user.electros.build
    #@hwater = current_user.hwaters.build
    #@cleaning = current_user.cleanings.build
    #@transport = current_user.transports.build

    #@papers = current_user.papers
    

	end

	def compare
		if current_user.profile
		#@user = User.find(params[:id])
		#@#users = User.friendships.friend(params[:id])
    @user = User.find_by(id: params[:to].to_i) if params[:to]

		@paper_weight_total_user = @user.papers.sum(:paper_weight) 
		@paper_weight_per_capita_user = @user.papers.sum(:paper_weight) / (@user.profile.staff) 
		@env_paper_weight_user = @user.papers.sum(:env_paper_weight)
		@env_paper_ratio_user = (@env_paper_weight_user / @paper_weight_total_user) * 100	

		@paper_tree_ratio_user = (@user.papers.sum(:paper_weight) / 1000) *15 
    	@paper_tree_co2_rescue_user = @paper_tree_ratio_user * (0.492)

    	#Rafmagn  
    	   @electro_total_user = @user.electros.sum(:electricity_kwst)
           @electro_total_per_capita_user = @user.electros.sum(:electricity_kwst) / @user.profile.staff 
           @electro_total_per_m2_user = @user.electros.sum(:electricity_kwst) / @user.profile.building_size
        #HotWater    
          @hwater_total_m3_user = @user.hwaters.sum(:hot_water_cubic_meter) 
           @hwater_total_m3_per_capita_user = @user.hwaters.sum(:hot_water_cubic_meter) /@user.profile.staff
           @hwater_m3_m2_ratio_user = @user.hwaters.sum(:hot_water_cubic_meter) / @user.profile.building_size   

        #Ræsting
           @cleaning_total_user = @user.cleanings.sum(:cleaning_liter)
           @cleaning_staff_ratio_user = @user.cleanings.sum(:cleaning_liter) / @user.profile.staff
           @cleaning_building_ratio_user = @user.cleanings.sum(:cleaning_liter) / @user.profile.building_size   

        #Ferðalog-bilar
           @transport_co2_km_user = @user.transports.sum(:transport_km) * (0.1404)
           @transport_co2_km_staff_ratio_user = @user.transports.sum(:transport_km) * (0.1404) / @user.profile.staff
           @transport_km_staff_ratio_user = @user.transports.sum(:transport_km) / @user.profile.staff
           @transport_km_user = @user.transports.sum(:transport_km)
        #Ferðalog-flug
          @transport_flight_co2_user = @user.transports.sum(:transport_flight_km) * (0.1722)   
          @transport_flight_co2_staff_ratio_user = @user.transports.sum(:transport_flight_km) * (0.1722) / @user.profile.staff
          @transport_flight_km_user = @user.transports.sum(:transport_flight_km) 
          @transport_flight_km_staff_ratio_user = @user.transports.sum(:transport_flight_km) / @user.profile.staff

        #Co2 vegna ferðalaga
          @co2_due_to_transport_user = (@transport_flight_co2 + @transport_co2_km) / 1000

          @tree_count_rescue_user = @co2_due_to_transport * 492    
	else
		redirect_to user_path
	end
	end

 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CircularV10</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>


	<p class="notice"><%= notice %></p>
 	<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/pages/_panels.html.erb
<div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">1. Orkuiðnaður</h3>
          <span class="pull-right clickable panel-collapsed"><i class="glyphicon glyphicon-chevron-up"></i></span>
        </div>
        <div class="panel-body">
          <li>1.1.  Brennslustöðvar með meiri nafnhitaafköst en 50 MW.</li>
          <li>1.2.  Jarðolíu- og gashreinsunarstöðvar.</li>
          <li>1.3.  Koksverksmiðjur.</li>
          <li>1.4.  Iðjuver þar sem kolagösun og þétting fer fram.</li>
        </div>
</div>

<div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">2. Framleiðsla og vinnsla málma</h3>
          <span class="pull-right clickable panel-collapsed"><i class="glyphicon glyphicon-chevron-up"></i></span>
        </div>
        <div class="panel-body">
         <li> 2.1.  Álframleiðsla.</li>
          <li>2.2.  Kísiljárnframleiðsla.</li>
          <li>2.3.  Kísilmálmframleiðsla.</li>
          <li>2.4.  Kísil- og kísilgúrframleiðsla.</li>
          <li>2.5.  Járn- og stálframleiðsla.</li>
          <li>2.6.  Sinkframleiðsla.</li>
          <li>2.7.  Framleiðsla á magnesíum og efnasamböndum sem innihalda magnesíum.</li>
        </div>
</div>

<div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">3.  Jarðefnaiðnaður</h3>
          <span class="pull-right clickable panel-collapsed"><i class="glyphicon glyphicon-chevron-up"></i></span>
        </div>
        <div class="panel-body">
          <li>3.1.  Sements- og kalkframleiðsla.</li>
          <li>3.2.  Stöðvar þar sem vinnsla asbests og framleiðsla vara sem innihalda asbest fer fram.</li>
          <li>3.3.  Glerullarframleiðsla. Stöðvar þar sem framleiðsla glers, einnig glertrefja, fer fram og sem geta brætt meira en 20 tonn á dag.</li>
          <li>3.4.  Steinullarframleiðsla. Stöðvar þar sem bræðsla jarðefna, einnig steinullartrefja, fer fram og sem geta brætt meira en 20 tonn á dag.</li>
          <li>3.5.  Stöðvar þar sem framleiðsla leirvara fer fram með brennslu, einkum þakflísa, múrsteina, eldfastra múrsteina, flísa, leirmuna eða postulíns, sem geta framleitt meira en 75 tonn á dag og/eða rúmtak ofns er meira en 4 m³ og setþéttleiki hans er meiri en 300 kg/m³.</li>
        </div>
</div>

<div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">4.  Efnaiðnaður.</h3>
          <span class="pull-right clickable panel-collapsed"><i class="glyphicon glyphicon-chevron-up"></i></span>
        </div>
        <div class="panel-body">
          <li>4.1.  Efnaverksmiðjur sem framleiða lífræn grunnefni, svo sem:</li>
             <ol>a)  einföld vetniskolefni,</ol> 
              <ol>b)  vetniskolefni með súrefni, svo sem alkóhól, aldehýð, ketón, karboxýlsýrur, estera, asetöt, etera, peroxíð, epoxýresín,</ol> 
              <ol>c)  brennisteinsvetniskolefni,</ol> 
              <ol>d)  köfnunarefnisvetniskolefni, svo sem amín, amíð, nítursambönd, nítrósambönd eða nítratsambönd, nítríl, sýanöt, ísósýanöt,</ol> 
              <ol>e)  vetniskolefni með fosfór,</ol> 
              <ol>f)  halógenvetniskolefni,</ol> 
              <ol>g)  lífræn málmsambönd,</ol> 
              <ol>h)  plastefni,</ol> 
              <ol>i)  gervigúmmí,</ol> 
              <ol>j)  litarefni og dreifuliti,</ol> 
              <ol>k)  yfirborðsvirk efni.</ol> 
            <li>4.2.  Efnaverksmiðjur sem framleiða ólífræn grunnefni, svo sem:</li>
             <ol> a)  gös, svo sem ammóníak, klór eða vetnisklóríð, flúor eða vetnisflúoríð, koloxíð,             brennisteinssambönd, köfnunarefnisoxíð, vetni, brennisteinsdíoxíð, karbónýlklóríð,</ol>
              <ol>b)  sýrur, svo sem krómsýru, flúorsýru, fosfórsýru, saltpéturssýru, saltsýru, brennisteinssýru, óleum, brennisteinstvísýrling,</ol>
              <ol>c)  basa, svo sem ammóníumhýdroxíð, kalíumhýdroxíð, natríumhýdroxíð,</ol>
              <ol>d)  sölt, svo sem ammóníumklóríð, kalíumklórat, kalíumkarbónat, natríumkarbónat, perbórat, silfurnítrat,</ol>
              <ol>e)  málmleysingja, málmoxíð eða önnur ólífræn sambönd, svo sem kalsíumkarbíð, kísil, kísilkarbíð.</ol>
            <li>4.3.  Áburðarframleiðsla. Efnaverksmiðjur sem framleiða áburð sem inniheldur fosfór, köfnunarefni eða kalíum (einnig áburðarblöndur).</li>
            <li>4.4.  Efnaverksmiðjur sem framleiða grunnvörur fyrir plöntuheilbrigði og sæfiefni.</li>
            <li>4.5.  Stöðvar þar sem notaðar eru efnafræðilegar og líffræðilegar aðferðir við framleiðslu grunnlyfjavara.</li>
            <li>4.6.  Efnaverksmiðjur sem framleiða sprengiefni.</li>
            <li>4.7.  Kítín- og kítosanframleiðsla.</li>
            <li>4.8.  Lím- og málningarvöruframleiðsla.</li>
        </div>
</div>



<div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">5. Úrgangsstarfsemi</h3>
          <span class="pull-right clickable panel-collapsed"><i class="glyphicon glyphicon-chevron-up"></i></span>
        </div>
        <div class="panel-body">
          <li>5.1.  Stöðvar fyrir meðhöndlun, förgun eða endurnýtingu spilliefna.</li>
          <li>5.2.  Stöðvar fyrir sorpbrennslu sem geta afkastað meira en 3 tonnum á klukkustund.</li>
          <li>5.3.  Stöðvar fyrir förgun úrgangs annars en spilliefna sem geta afkastað meira en 50 tonnum á dag.</li>
          <li>5.4.  Urðunarstaðir sem taka við meira en 10 tonnum á dag eða geta afkastað meira í heild en 25.000 tonnum af óvirkum úrgangi.</li>
        </div>
</div>


<div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">6.  Önnur starfsemi</h3>
          <span class="pull-right clickable panel-collapsed"><i class="glyphicon glyphicon-chevron-up"></i></span>
        </div>
        <div class="panel-body">
         <li> 6.1.  Pappírs- og trjákvoðuframleiðsla. Iðjuver sem framleiða:</li>
            <ol>a)  deig úr viði eða önnur trefjaefni,</ol>
            <ol>b)  pappír og pappa og geta framleitt meira en 20 tonn á dag.</ol>
          <li>6.2.  Stöðvar þar sem fram fer formeðferð eða litun trefja eða textílefna og vinnslugeta er meiri en 10 tonn á dag.</li>
          <li>6.3.  Sútunarverksmiðjur. Stöðvar þar sem fram fer sútun á húðum og skinnum og vinnslugeta er meiri en 12 tonn af fullunninni vöru á dag.</li>
         <li> 6.4.  Matvælavinnsla:</li>
            <ol>a)  Sláturhús sem geta framleitt meira en 50 tonn af skrokkum á dag.</ol>
            
              <ol>b)  Meðferð og vinnsla fyrir matvælaframleiðslu úr:
                      <li class="small"> - hráefnum af dýrum, öðrum en mjólk, þar sem hægt er að framleiða meira en 75 tonn af fullunninni vöru á dag,</li>
                      <li class="small"> - hráefnum af jurtum þar sem hægt er að framleiða að meðaltali meira en 300 tonn af fullunninni vöru á dag.</li>
                      </ol>

                 <ol> c)  Meðferð og vinnsla mjólkur, tekið er á móti meira en 200 tonnum af mjólk á dag miðað við meðaltal á ársgrundvelli. </ol>   

                <li> 6.5. Stöðvar þar sem förgun eða endurvinnsla skrokka og úrgangs af dýrum fer fram og afkastageta er meiri en 10 tonn á dag.</li>
                <li> 6.6.  Stöðvar þar sem þauleldi alifugla eða svína fer fram með fleiri en:</li>
                    
                      <ol>a)  40.000 stæði fyrir alifugla, </ol>
                      <ol>b)  2.000 stæði fyrir alisvín yfir 30 kg eða </ol>
                      <ol>c)  750 stæði fyrir gyltur. </ol>
                      
                <li>6.7.  Stöðvar þar sem fram fer yfirborðsmeðferð efna, hluta eða afurða með lífrænum leysiefnum, einkum pressun, prentun, húðun, fituhreinsun, vatnsþétting, meðhöndlun eða þakning með límvatni, málun, hreinsun eða gegndreyping og meira en 150 kg eru notuð á klukkustund eða meira en 200 tonn á ári.</li>
                <li>6.8.  Stöðvar þar sem fram fer framleiðsla kolefna eða rafgrafíts með brennslu eða umbreytingu í grafít.</li>
                <li>6.9.  Fiskimjölsverksmiðjur með meiri framleiðsluafköst en 400 tonn á sólarhring.</li>
                <li>6.10. Eldi sjávar- og ferskvatnslífvera þar sem ársframleiðsla er meiri en 200 tonn og fráveita til sjávar eða ársframleiðsla er meiri en 20 tonn og fráveita í ferskvatn.</li>
                <li>6.11. Olíumalar- og malbikunarstöðvar með fasta staðsetningu.</li>      

          </div>
</div>


<script type="text/javascript">
$(document).on('click', '.panel-heading span.clickable', function(e){
    var $this = $(this);
  if(!$this.hasClass('panel-collapsed')) {
    $this.parents('.panel').find('.panel-body').slideUp();
    $this.addClass('panel-collapsed');
    $this.find('i').removeClass('glyphicon-chevron-up').addClass('glyphicon-chevron-down');
  } else {
    $this.parents('.panel').find('.panel-body').slideDown();
    $this.removeClass('panel-collapsed');
    $this.find('i').removeClass('glyphicon-chevron-down').addClass('glyphicon-chevron-up');
  }
})
</script>

app/views/pages/index.html.erb
<div class="container">
	
	<div class="row">
		<div class="col-md-6">
			<div class="well">
 				 <div><h3>Skilaskyld fyrirtæki</h3></div>
  				 <div >Skilaskyld fyrirtæki færa grænt bókhald og skýrslur um grænt bókhald fyrir starfsleyfisskylda starfsemi samkv. reglugerð nr.851-2002.
  				 
  				 <%= render 'pages/panels' %>
  				 </div>
  				 <%= link_to 'Skrá Grænt Bókhald', new_user_registration_path, class: 'btn btn-primary' %>

			</div>
		</div>

		<div class="col-md-6">
			<div class="panel panel-default">
 				 <div class="panel-heading"><h3>Fyrirtæki án skilaskyldu</h3></div>
  				 <div class="panel-body">Fyrirtæki sem færa ekki grænt bókhald samkv. reglugerð nr.851-2002.</div>
  				 <%= link_to 'Skrá Grænt Bókhald', root_path, class: 'btn btn-primary' %>
			</div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
Users index

app/views/users/show.html.erb
<h1> Show Users</h1>


<div class="container">
<div class="col-md-12 col-md-offset-1">
        <div class="col-md-3 user-box-top">
        <p><small>Síðast Innskráð: <%=current_user.last_sign_in_at %></small></p>
        <% if current_user.profile %>
          <p>Fyrirtæki: <%=current_user.profile.company_name%></p>
          <p>Fjöldi stöðugilda: <%#=current_user.profile.staff %></p>
          <%= link_to "Uppfæra skráningu", edit_user_profile_path(current_user) %>
             <%= link_to "Skoða skráningu", users_path(current_user)%>
        <% end %>          
    
       </div>  
</div>